### PR TITLE
Use Bundler to manage gem dependencies

### LINKED ISSUE #27: Install via Gemfile?
Is there any specific reason we wish to put the `gem install`s directly in the Dockerfile or could we [use a Gemfile](https://github.com/kubernetes/contrib/blob/master/fluentd/fluentd-gcp-image/Dockerfile#L38) for each permutation?

### PR DESCRIPTION
**Pull request by errm**
* Makes builds more deterministic
* Avoids issues with plugin incompatibility with fluentd version
* Vulnerability scanning from github
* ~ moves a little closer to solving #43 perhaps
* Fixes #27

### CODE REVIEW

**Comment by errm** [comment]
Also fixes #69

**Comment by edsiper** [comment]
@repeatedly any comments on using Bundler instead of gem utility ?

**Comment by repeatedly** [comment]
Gemfile based plugin management is easier than list of install command.
So the approach seems good for me.

**Comment by errm** [comment]
I am working on rebasing this PR on the recent changes ...

**Comment by errm** [comment]
Rebase seems good... I had to add git to the build process to cover the gems that are now being installed from git repos. @edsiper could you take another look?

**Comment by repeatedly** [comment]
@edsiper Do you have any concern? We need to release v1 based images so need to merge this change before.

**Comment by repeatedly** [comment]
@edsiper Can we merge?

**Comment by repeatedly** [comment]
No counter opinion. Merged. Thanks!

**Pull request merged**
