### PR TITLE
Add debian based images

### PR DESCRIPTION
**Pull request by chancez**
Also adds the fluentd-plugin-systemd gem + config for debian based images

Note that this PR changes the folder layout in `docker-images/`, so it may
require updating automated docker builds if it depends on the folder structure.

### CODE REVIEW

**Comment by chancez** [comment]
The 1st commit updates the Makefile + templates, the 2nd commit is the result of re-running `make src-all`, so it's all generated output.

The last commit adds the systemd plugin to the debian based images + regenerates.

**Comment by chancez** [comment]
The 1st commit updates the Makefile + templates, the 2nd commit is the result of re-running `make src-all`, so it's all generated output.

The 3rd commit updates the Makefile + templates to install and configure the systemd plugin for debian images.
The 4th commit regenerates the docker-images directory with the systemd plugin changes.

**Comment by chancez** [comment]
I've got the ES debian image built here: https://quay.io/repository/coreos/fluentd-kubernetes?tab=tags in case you would like to try/look. I've tested this on my Kubernetes cluster and it works great so far. I'm seeing systemd logs, and fluentd is running as expected.

**Comment by edsiper** [comment]
@so0k @c-knowles : since you helped to put in place #4, would you please help to review these changes ?

**Comment by so0k** [comment]
I'll have a look

**Comment by so0k** [comment]
Sorry, didn't have time yet to review - glancing over https://github.com/coreos/fluentd-kubernetes-daemonset/tree/add_debian_image - seems README is not updated yet?

**Comment by chancez** [comment]
@so0k Updated the README.

**Comment by so0k** [comment]
Thanks @chancez - I've merged your changes to [my fork](https://github.com/honestbee/fluentd-kubernetes) (which has automated docker hub builds as well...). 

Unfortunately, relative links in the `README` don't work on [DockerHub](https://hub.docker.com/r/honestbee/fluentd-kubernetes/) - so ideally these are still full URLs (sorry for the inconvenience).

Apart from that, LGTM.

@edsiper - when these changes are merged, it is needed to update the build settings on the Docker Hub repository as follows:

- Update the `dockerfile location` for each tag
- Add builds for the debian tags

Final result looks like:

image

**Comment by chancez** [comment]
@so0k I can update the URLs then. One moment.

**Comment by chancez** [comment]
I removed the last commit which used relative URLs. I think it should be correct now. (Urls will be broken since the locations of files changed, and the links point to master).

**Comment by so0k** [comment]
@edsiper - I believe this can be merged (as well as need to update the docker hub builds)

**Comment by edsiper** [comment]
thanks for the review.

@so0k how the build settings should looks like ?

**Comment by so0k** [comment]
There's a picture here but small mistake, see note

https://github.com/fluent/fluentd-kubernetes-daemonset/pull/12#issuecomment-299959862

**Comment by edsiper** [comment]
what do you think about to get rid of Alpine based images ? 

@chancez I see the Alpine images don't use Jemalloc, to support Alpine we need Jemalloc on it, otherwise memory fragmentation on Fluentd side will be high.

**Comment by chancez** [comment]
@edsiper I didn't touch alpine, so that's irrelevant to this PR IMO.

**Comment by edsiper** [comment]
@chancez actually this PR adds Alpine based images:

```
./docker-image/v0.12/alpine-elasticsearch
./docker-image/v0.12/alpine-elasticsearch/plugins
./docker-image/v0.12/alpine-elasticsearch/plugins/parser_kubernetes.rb
./docker-image/v0.12/alpine-elasticsearch/plugins/.gitkeep
./docker-image/v0.12/alpine-elasticsearch/conf
./docker-image/v0.12/alpine-elasticsearch/conf/systemd.conf
./docker-image/v0.12/alpine-elasticsearch/conf/fluent.conf
./docker-image/v0.12/alpine-elasticsearch/conf/kubernetes.conf
./docker-image/v0.12/alpine-elasticsearch/Dockerfile
./docker-image/v0.12/alpine-elasticsearch/hooks
./docker-image/v0.12/alpine-elasticsearch/hooks/post_push
./docker-image/v0.12/alpine-elasticsearch/.dockerignore
./docker-image/v0.12/alpine-cloudwatch
./docker-image/v0.12/alpine-cloudwatch/plugins
./docker-image/v0.12/alpine-cloudwatch/plugins/parser_kubernetes.rb
./docker-image/v0.12/alpine-cloudwatch/plugins/.gitkeep
./docker-image/v0.12/alpine-cloudwatch/conf
./docker-image/v0.12/alpine-cloudwatch/conf/systemd.conf
./docker-image/v0.12/alpine-cloudwatch/conf/fluent.conf
./docker-image/v0.12/alpine-cloudwatch/conf/kubernetes.conf
./docker-image/v0.12/alpine-cloudwatch/Dockerfile
./docker-image/v0.12/alpine-cloudwatch/hooks
./docker-image/v0.12/alpine-cloudwatch/hooks/post_push
./docker-image/v0.12/alpine-cloudwatch/.dockerignore
./docker-image/v0.12/alpine-loggly
./docker-image/v0.12/alpine-loggly/plugins
./docker-image/v0.12/alpine-loggly/plugins/parser_kubernetes.rb
./docker-image/v0.12/alpine-loggly/plugins/.gitkeep
./docker-image/v0.12/alpine-loggly/conf
./docker-image/v0.12/alpine-loggly/conf/systemd.conf
./docker-image/v0.12/alpine-loggly/conf/fluent.conf
./docker-image/v0.12/alpine-loggly/conf/kubernetes.conf
./docker-image/v0.12/alpine-loggly/Dockerfile
./docker-image/v0.12/alpine-loggly/hooks
./docker-image/v0.12/alpine-loggly/hooks/post_push
./docker-image/v0.12/alpine-loggly/.dockerignore
./docker-image/v0.12/alpine-logentries
./docker-image/v0.12/alpine-logentries/plugins
./docker-image/v0.12/alpine-logentries/plugins/out_logentries.rb
./docker-image/v0.12/alpine-logentries/plugins/parser_kubernetes.rb
./docker-image/v0.12/alpine-logentries/conf
./docker-image/v0.12/alpine-logentries/conf/systemd.conf
./docker-image/v0.12/alpine-logentries/conf/fluent.conf
./docker-image/v0.12/alpine-logentries/conf/kubernetes.conf
./docker-image/v0.12/alpine-logentries/Dockerfile
./docker-image/v0.12/alpine-logentries/hooks
./docker-image/v0.12/alpine-logentries/hooks/post_push
./docker-image/v0.12/alpine-logentries/.dockerignore
```

**Comment by chancez** [comment]
@edsiper no, it merely moves the existing alpine generated files to a different directory structure to accommodate multiple base images. The current images use alpine, I'm adding debian.

**Comment by edsiper** [comment]
Thanks for the clarification, my fault!

**Comment by edsiper** [comment]
@chancez would you please check the conflict ?, once fixed I will merge it.

**Comment by chancez** [comment]
@edsiper I opened another PR https://github.com/fluent/fluentd-kubernetes-daemonset/pull/20 because the conflict is due to the fact that a change you made was done directly to the generated file instead of the template file. Once that's merged, I'll be rebasing on top of that to fix this.

**Comment by edsiper** [comment]
#20 merged

**Comment by chancez** [comment]
@edsiper Rebased.

**Comment by so0k** [comment]
I can fix readme links and loook into alpine issues after this is merged

**Comment by edsiper** [comment]
@so0k @chancez thank you!

I strongly think we should deprecate Alpine linux based images.

**Comment by so0k** [comment]
@edsiper are you referring to this https://bugs.alpinelinux.org/issues/5389?

**Comment by edsiper** [comment]
@so0k that one and others. Personally I have to stop working with Alpine with https://github/fluent/fluent-bit because of jemalloc and other Musl compatibility issues.

**Pull request merged**
