### PR TITLE
Release v1.18.0 images

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by daipom** [comment]
Thanks!
Don't we remove these template files?

* https://github.com/fluent/fluentd-kubernetes-daemonset/blob/bb2e69ed03c7693c4ba9a8f98b3b3d04290870f2/templates/post_checkout.erb
* https://github.com/fluent/fluentd-kubernetes-daemonset/blob/bb2e69ed03c7693c4ba9a8f98b3b3d04290870f2/templates/post_push.erb

**Comment by kenhys** [comment]
It should be removed. Thanks.

**Review by daipom — APPROVED** [review]
LGTM! Thanks!

**Review by Watson1978 — APPROVED** [review]
👍🏻

**Pull request merged**
