### PR TITLE
Fix graylog connecting issue

### PR DESCRIPTION
**Pull request by kenhys**
Closes: #1479

Feedback from @mszyzdek
ref. https://github.com/fluent/fluentd-kubernetes-daemonset/issues/1479#issuecomment-1996018837

* graylog flavour of fluentd-kubernetes-daemonset uses gelf 3.0.0 and this version of gelf gem has Fixnum in code, https://github.com/graylog-labs/gelf-rb/commit/7cc3cbb63556f54967699e034b1d51cf30bf1c6f
* in ruby 3.2 Fixnum was removed after previous deprecation in version 2.4 https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
* ruby in newest fluentd was upgraded to 3.2 https://github.com/fluent/fluentd-docker-image/commit/4f1d5e8dcdbbed10d1458edaecfb771f6ba9f05e so it also happened in fluentd-kubernetes-daemonset
* gelf 3.0.0 cannot work with ruby 3.2+ so we can see sad error on container start

### CODE REVIEW

**Comment by daipom** [comment]
https://github.com/fluent/fluentd-kubernetes-daemonset/issues/1479#issuecomment-2222335839

Sorry, I don't understand #219.
Can we revert #219 now?

**Comment by kenhys** [comment]
Oh, gelf-rb/issues/63 is still brocker.

**Comment by kenhys** [comment]
For graylog, fluent-plugin-json-in-json-2 depends on yajl-ruby...

**Comment by daipom** [comment]
Thanks. I see...

**Comment by kenhys** [comment]
TODO: eliminate yajl-ruby (yajl/json_gem)

**Comment by kenhys** [comment]
Purge yajl/json_gem explicitly from image?

**Comment by daipom** [comment]
https://github.com/fluent/fluentd-kubernetes-daemonset/issues/1479#issuecomment-2224777455

The issue of `gelf-rb 3.1.0` remains partially.

**Review by daipom — APPROVED** [review]
Thanks! LGTM.
Although `gelf 3.1.0` has a remaining issue, we should update it because the impact is limited to not being able to `SIGUSR2` to reload the config.

**Comment by kenhys** [comment]
Thanks, after #1507 was merged, let's ship it.

**Pull request merged**
