### PR TITLE
Upgrade Ruby to 2.7

### LINKED ISSUE #1336: v1.14.5 images are broken due to mismatched Ruby version
Hello, I'm currently investigating an issue with my kubernetes cluster. It appears that the latest build of `fluent/fluentd-kubernetes-daemonset:v1.14-debian-elasticsearch7-1` is failing to start up. according to kubernetes, the pod is crash looping with an exit code of 1. Nodes there are older than 3 hours old seem fine, and nodes that are younger than 3 hours seem to crash loop. I've included an example pod spec below, but there appears to be no logs, and the readme on dockerhub doesn't include any info how to enable debug level logs.

In the short term, I've temporarily changed my daemonset to target an older version by sha instead of using the tag.

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2022-02-14T05:31:10Z"
  generateName: fluentd-
  labels:
    app: fluentd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "1.0"
    controller-revision-hash: 54cff5888c
    helm.sh/chart: fluentd
    pod-template-generation: "4"
  name: fluentd-b8ncv
  namespace: common-logging
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: fluentd
    uid: cbc2b465-f073-4693-8199-c26a3c9e93a2
  resourceVersion: "1054909545"
  uid: 5b6ad221-e0f0-4492-8025-76374edeac66
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - ip-10-128-101-237.us-west-2.compute.internal
  containers:
  - env:
    - name: FLUENT_ELASTICSEARCH_HOST
      value: elastic-common-es-http.common-logging.svc.cluster.local
    - name: FLUENT_ELASTICSEARCH_PORT
      value: "9200"
    - name: FLUENT_ELASTICSEARCH_SCHEME
      value: https
    - name: FLUENT_UID
      value: "0"
    - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
      value: "false"
    - name: FLUENT_ELASTICSEARCH_SSL_VERSION
      value: TLSv1_2
    - name: FLUENT_ELASTICSEARCH_USER
      value: fluentd
    - name: FLUENT_ELASTICSEARCH_PASSWORD
      value: <secret>
    - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
      value: '[]'
    - name: FLUENT_ELASTICSEARCH_LOGSTASH_PREFIX
      value: fluentd-default
    image: fluent/fluentd-kubernetes-daemonset:v1.14-debian-elasticsearch7-1
    imagePullPolicy: IfNotPresent
    name: fluentd
    resources:
      limits:
        cpu: 500m
        memory: 750Mi
      requests:
        cpu: 500m
        memory: 750Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log
      name: varlog
    - mountPath: /var/lib/docker/containers
      name: varlibdockercontainers
      readOnly: true
    - mountPath: /fluentd/etc/conf.d
      name: fluentd-configuration
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: fluentd-token-r4qg8
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-128-101-237.us-west-2.compute.internal
  preemptionPolicy: PreemptLowerPriority
  priority: 1000000
  priorityClassName: high-priority
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: fluentd
  serviceAccountName: fluentd
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - configMap:
      defaultMode: 420
      name: fluentd-configuration
    name: fluentd-configuration
  - hostPath:
      path: /var/log
      type: ""
    name: varlog
  - hostPath:
      path: /var/lib/docker/containers
      type: ""
    name: varlibdockercontainers
  - name: fluentd-token-r4qg8
    secret:
      defaultMode: 420
      secretName: fluentd-token-r4qg8
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-02-14T05:31:10Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-02-14T05:31:10Z"
    message: 'containers with unready status: [fluentd]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-02-14T05:31:10Z"
    message: 'containers with unready status: [fluentd]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-02-14T05:31:10Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://89007721aabaa5e14101685c803c2301cd6e2ebf776d70d37ba5ff1f8492ea37
    image: fluent/fluentd-kubernetes-daemonset:v1.14-debian-elasticsearch7-1
    imageID: docker-pullable://fluent/fluentd-kubernetes-daemonset@sha256:ca6757a31e009bdab8334703970baf4b04430cfb2d72684af9a0dc3247d200fc
    lastState:
      terminated:
        containerID: docker://7640fd74ea4b8812f1b281be9df00a70573d9d09cb6ffa32bcad8b5cee86352e
        exitCode: 1
        finishedAt: "2022-02-14T05:41:51Z"
        reason: Error
        startedAt: "2022-02-14T05:41:51Z"
    name: fluentd
    ready: false
    restartCount: 8
    started: false
    state:
      terminated:
        containerID: docker://89007721aabaa5e14101685c803c2301cd6e2ebf776d70d37ba5ff1f8492ea37
        exitCode: 1
        finishedAt: "2022-02-14T05:47:01Z"
        reason: Error
        startedAt: "2022-02-14T05:47:00Z"
  hostIP: 10.128.101.237
  phase: Running
  podIP: 10.128.99.147
  podIPs:
  - ip: 10.128.99.147
  qosClass: Guaranteed
  startTime: "2022-02-14T05:31:10Z"
```

### PR DESCRIPTION
**Pull request by ashie**
Upgrade Ruby version from 2.6 to 2.7.
Fix #1336

Signed-off-by: Takuro Ashie <ashie@clear-code.com>

### CODE REVIEW

**Comment by ashie** [comment]
Cannot generate files due to server error of https://dl-cdn.alpinelinux.org/. Wait for a while...

**Comment by kenhys** [comment]
Just for regenerating files, we can use one of mirrors for a while.

https://mirrors.alpinelinux.org/

```diff
diff --git a/Makefile b/Makefile
index d3af6b90..ab90b91d 100644
--- a/Makefile
+++ b/Makefile
@@ -194,7 +194,7 @@ dockerfile-all:
 gemfile:
        make container-image-template FILE=Gemfile
        docker run --rm -i -v $(PWD)/docker-image/$(DOCKERFILE)/Gemfile:/Gemfile:ro \
-               ruby:alpine sh -c "apk add --no-cache --quiet git && bundle lock --print --remove-platform x86_64-linux-musl --add-platform ruby" > docker-image/${DOCKERFILE}/Gemfile.lock
+               ruby:alpine sh -c "sed -i 's,https://dl-cdn.alpinelinux.org,http://dl-4.alpinelinux.org,g' /etc/apk/repositories && apk add --no-cache --quiet git && bundle lock --print --remove-platform x86_64-linux-musl --add-platform ruby" > docker-image/${DOCKERFILE}/Gemfile.lock
 
```

**Comment by kenhys** [comment]
It seems that https://dl-cdn.alpinelinux.org/ is back to normal.

**Review by fujimotos — APPROVED** [review]

**Review by kenhys — APPROVED** [review]
LGTM.

**Pull request merged**
