### PR TITLE
Use microbadger for layers/sizes in README

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by gliptak** [comment]
@repeatedly please review

**Comment by repeatedly** [comment]
Is this site active? Why the page shows older version, not latest?

**Comment by gliptak** [comment]
From what I observed, the site expects ```latest``` tag which this project doesn't use.

**Comment by repeatedly** [comment]
How to automatically update the info without latest tag?
Can we pull or push to this site?

**Comment by gliptak** [comment]
@repeatedly I have limited familiarity with microbadger other projects started using it after imagelayers are no longer maintained

https://microbadger.com/images/fluent/fluentd-kubernetes-daemonset does have a Webhook

image

PS would it be customary to publish a ```latest``` tag for many Docker images?

**Pull request closed without merging**
