### PR TITLE
Adding splunk HEC support

### PR DESCRIPTION
**Pull request by FutureSharks**
I built the container and tested it in our environment and it works well 🙂

### CODE REVIEW

**Comment by max-rocket-internet** [comment]
Hi @repeatedly could we get this PR merged?

**Comment by max-rocket-internet** [comment]
Any update @repeatedly?

**Comment by repeatedly** [comment]
Need debian images and please add your name to README's maintainer section:

https://github.com/fluent/fluentd-kubernetes-daemonset#maintainers

**Comment by max-rocket-internet** [comment]
@repeatedly done and done

**Comment by repeatedly** [comment]
sorry for the late. Merged!

**Comment by max-rocket-internet** [comment]
No worries, thanks @repeatedly 🙂

**Comment by cdaringe** [comment]
a little more documentation would go a long way here.  ive been scratchin at this for a bit.  i see in `-vv` mode some contact being made (but not showing up in my indicies), but not sure what else is needed.  not sure what all switches i need to flip on for everything to be zen.  anyway, thx for making the effort to get something out at all :)

**Comment by max-rocket-internet** [comment]
@cdaringe it might help to rule out fluentd for now and just test your HEC with curl: http://dev.splunk.com/view/event-collector/SP-CAAAE7F

Then find your message in your Splunk, work out the index etc.

**Comment by cdaringe** [comment]
Thanks. I meant to follow up. This plugin was doing great work, but splunk was tossing away the data due to an issue I'm still working out. Thanks for the feedback!

**Pull request merged**
