### PR TITLE
Update fluent-plugin-cloudwatch-logs to v0.7.3

### PR DESCRIPTION
**Pull request by cosmo0920**
Because v0.7.2 implementation contains a typo. :cry:
This typo is reported in https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/pull/141.

Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>

### CODE REVIEW

**Comment by repeatedly** [comment]
Could you update minor version of cloudwatch image?

**Comment by cosmo0920** [comment]
Where is minor version of cloudwatch image...?

**Comment by repeatedly** [comment]
Here: https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/Makefile#L18
like https://github.com/fluent/fluentd-kubernetes-daemonset/commit/d9e95ad0aaab5ed5e24b64f9b16461fff579c34a

**Comment by cosmo0920** [comment]
Oh! I've got it.
I updated the PR to reflect your advice. :smile:

**Comment by repeatedly** [comment]
Thx!

**Pull request merged**
