### PR TITLE
Give the option to configure the path on elasticsearch

### PR DESCRIPTION
**Pull request by vigohe**

### CODE REVIEW

**Comment by repeatedly** [comment]
@cosmo0920 Does empty string valid for `path` parameter? By default, `ENV['FLUENT_ELASTICSEARCH_PATH']` is nil so it becomes empty string in `configure`.

**Comment by cosmo0920** [comment]
Es plugin just pass through `path` parameter and other connection parameters into `elasticsearch-ruby`.
It seems that empty string is valid for `path`.
Because it is used in string interpolation: https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/transport/base.rb#L238

**Comment by repeatedly** [comment]
@cosmo0920 Thanks.

@vigohe If you want to apply this change to images, please run `make src-all`.

**Comment by repeatedly** [comment]
Sorry for the late. Just merged.

**Comment by vigohe** [comment]
Thanks 💪

**Pull request merged**
