### PR TITLE
Add Papertrail Support

### PR DESCRIPTION
**Pull request by alexouzounis**
- [X] Add Alpine and Debian images for Papertrail
- [X] Add Kubernetes Daemonset example for Papertrail
- [X] Use ~~@loz's~~ SolarWinds' Fluent Papertrail plugin ~~https://github.com/loz/fluent-plugin-papertrail~~ https://github.com/solarwinds/fluent-plugin-papertrail
- [X] Add audit log support
- [X] Add bootkube support

### CODE REVIEW

**Comment by alexouzounis** [comment]
@ edsiper Could you have a look when time permits ? :)

**Comment by alexouzounis** [comment]
Until this gets merged - the images is being published at our repo in Quay

[Docker Repository on Quay](https://quay.io/repository/solarwinds/fluentd-kubernetes)

**Comment by alexouzounis** [comment]
Hey @edsiper - let me know if this looks good to you as I would love to have a PaperTrail integration here.
cc'ing @ leecalcote

**Comment by leecalcote** [comment]
@edsiper what are your thoughts here?

**Comment by leecalcote** [comment]
Thanks, @edsiper!

**Comment by alexouzounis** [comment]
@edsiper many thanks for merging this - any idea why the relevant tags were not created ?

https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/tags/
https://hub.docker.com/r/fluent/fluentd-kubernetes-daemonset/builds/

What is the command docker hub runs to build ?

**Comment by edsiper** [comment]
@leecalcote u're welcome, my apologizes for the delay.

@alexouzounis I plan to trigger the build tonight together with some test images based on Fluentd 1.0

**Comment by edsiper** [comment]
FYI: Images already available.

**Comment by alexouzounis** [comment]
excellent - many thanks :D

**Comment by Stelminator** [comment]
This has the side-effect of installing fluentd-1.1.0 in the debian images via `apt-get upgrade`.

**Pull request merged**
