### PR TITLE
Feature/debian-s3 support parquet compress

### PR DESCRIPTION
**Pull request by ChihSeanHsu**
For support parquet compress.
1. upgrade fluent-s3-plugin to 1.6.0
2. install columnfy 0.1.0

### CODE REVIEW

**Comment by kenhys** [comment]
Thanks!

but we don't directly modify these files.

Could you follow
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/MAINTAINING.md#updating ?

**Comment by ChihSeanHsu** [comment]
Hi @kenhys ,
Okay, I see. I'll modify it.
Do I need to re-generate all the different plugins or just for S3?

**Comment by kenhys** [comment]
Use `<% if target == "s3" %>...<% end %>` in Dockerfile.erb, then regenerating just for s3 is enough.

**Comment by ChihSeanHsu** [comment]
Hi @kenhys ,
Do I need to update all the files in docker-image or just these two template files?

**Review by kenhys — APPROVED** [review]
It's ok modifying template files.

LGTM.

**Comment by kenhys** [comment]
Thanks  @chancez

**Pull request merged**
