### PR TITLE
Update azure-blob-lts & misc

### LINKED ISSUE #1431: Bundler version
Good day all. 
Is there any plan to update the version of Bundler used in the 1.16-deb-elastic 7 and 8?
Our scan tools have picked up a few high findings in regards to the current version 2.2.15 it looks like 2.2.33 would resolve these findings. It looks like 2.2.34 is latest 2.2.x release https://rubygems.org/gems/bundler/versions/2.2.34

### PR DESCRIPTION
**Pull request by elsesiy**
- Bump azure-blob lts plugin to 0.7.0 (to pick up https://github.com/elsesiy/fluent-plugin-azure-storage-append-blob-lts/pull/13)
- Bump bundler in final image to 2.4.13 (fix #1431)
- Pin ruby:alpine version to match ruby version used throughout (3.1)

### CODE REVIEW

**Comment by elsesiy** [comment]
@ashie Can you take a look please? Thanks!

**Comment by elsesiy** [comment]
@ashie Friendly nudge, thanks!

**Comment by elsesiy** [comment]
@ashie Can you please take a look? Thanks!

**Review by ashie — CHANGES_REQUESTED** [review]
Thanks, and sorry for the delay.

* I prefer splitting commits with in following 2 things
  * Updating Makefile & templates
  * Auto generated files
* Need to update versions for other images since gems in them are also updated
*

**Comment by ashie** [comment]
I'll merge changes in this PR to #1446, thanks for you contribution!

**Pull request closed without merging**
