### PR TITLE
Fix missing Graylog tag in fluentd.conf file and fix Gemfile to corre…

### PR DESCRIPTION
**Pull request by tchelovilar**
Fix missing Graylog tag in fluentd.conf file and fix Gemfile to correct download a gelf gem.

### CODE REVIEW

**Comment by errm** [comment]
LGTM ... 

you just need to sign-off your commit:

```
git commit --amend -s
```

**Comment by repeatedly** [comment]
yes.
After recommit with `-s`, I will merge the patch.

**Comment by tchelovilar** [comment]
Sorry, tomorrow I'll recommit with -s.

**Comment by tchelovilar** [comment]
Recommited.

**Comment by repeatedly** [comment]
Thanks!

**Pull request merged**
