### PR TITLE
Add v1.10.1

### PR DESCRIPTION
**Pull request by elsesiy**
Fix deprecation warning for fluent.** logs

### CODE REVIEW

**Comment by elsesiy** [comment]
@repeatedly Please take a look

**Comment by repeatedly** [comment]
Thanks!

**Comment by elsesiy** [comment]
@repeatedly Sure! I assume you're publishing the new images as I couldn't find a job that takes care that, right?

**Comment by repeatedly** [comment]
Please wait. docker hub destroyed our build rules again. I'm now re-creating our setup on docker hub build page.

**Pull request merged**
