### PR TITLE
Upgrade fluent-plugin-azure-storage-append-blob version

### PR DESCRIPTION
**Pull request by nilsga**
Upgrade fluent-plugin-azure-storage-append-blob version to 0.2.0, which
supports MSI.

### CODE REVIEW

**Comment by elsesiy** [comment]
@nilsga I just merged the changes to the plugin. Can you please also update the `fluentd-daemonset-azureblob.yaml` example to include all available envs and the `fluent.conf.erb` accordingly? If not I can do it this weekend as this was on my list anyway.

**Comment by nilsga** [comment]
Ok, I'll do that. I didn't add anything, on purpose, since the defaults were fine, and more complex configuration required custom ConfigMap configuration anyway.

**Comment by elsesiy** [comment]
looks great, thanks @nilsga. Do you mind adding the `AZUREBLOB_SAS_TOKEN` as an option to the manifest as well? Then we have all options covered

**Review by cosmo0920 — APPROVED** [review]

**Comment by cosmo0920** [comment]
I'll publish a new image tag which includes this change. Thank you for your work!

**Pull request merged**
