### PR TITLE
Add Fluentd v1.13.0 images

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by cosmo0920** [comment]
Oh, #575 change is included in this PR! :open_mouth:

**Review by cosmo0920 — CHANGES_REQUESTED** [review]
I think that we shouldn't skip to publish Fluentd v1.13.0 images on daemonset.

**Review by cosmo0920 — APPROVED** [review]
Let's merge and publish then! :+1:

**Comment by kenhys** [comment]
updated build configuration to v1.13.

**Comment by kenhys** [comment]
running builds.

**Pull request merged**
