### PR TITLE
FluentD 1.10.3 & other minor changes

### PR DESCRIPTION
**Pull request by elsesiy**
Update to fluentd 1.10.3
Set bundler to 2.1.4 to match generated images
Make bash/sh scripts more portable by using /usr/bin/env shell instead of hard-coded /bin/shell
Update Dockerfiles

Signed-off-by: Jonas-Taha El Sesiy <github@elsesiy.com>

### CODE REVIEW

**Comment by repeatedly** [comment]
Sorry for the delay. Thanks!

**Comment by repeatedly** [comment]
After applied this changes, I can't run fluentd locally.
Does anyone know why? My Docker on Mac issue?

```
% docker run -p 24224:24224 -p 24224:24224/udp -v /tmp:/fluentd/log dccbae195720
[FATAL tini (6)] exec /fluentd/entrypoint.sh failed: No such file or directory
```

With v1.10.2 image, launch fluentd is succeeded.

```
# error is no problem
% docker run -p 24224:24224 -p 24224:24224/udp -v /tmp:/fluentd/log 97b73a2cf232
(eval):3:in `fetch': key not found: "KUBERNETES_SERVICE_HOST" (KeyError)
	from (eval):3:in `eval_embedded_code'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/literal_parser.rb:193:in `instance_eval'
```

**Comment by elsesiy** [comment]
@repeatedly Works for me:
```
docker run -p 24224:24224 -p 24224:24224/udp -v /tmp:/fluentd/log cbb3b09751b4
(eval):3:in `fetch': key not found: "KUBERNETES_SERVICE_HOST" (KeyError)
	from (eval):3:in `eval_embedded_code'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/literal_parser.rb:193:in `instance_eval'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/literal_parser.rb:193:in `eval_embedded_code'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/literal_parser.rb:109:in `scan_double_quoted_string'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/literal_parser.rb:82:in `scan_string'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/literal_parser.rb:75:in `parse_literal'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/v1_parser.rb:130:in `parse_element'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/v1_parser.rb:95:in `parse_element'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/v1_parser.rb:168:in `block in eval_include'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/v1_parser.rb:162:in `each'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/v1_parser.rb:162:in `eval_include'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/v1_parser.rb:145:in `parse_include'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/v1_parser.rb:104:in `parse_element'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/v1_parser.rb:43:in `parse!'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config/v1_parser.rb:33:in `parse'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config.rb:58:in `parse'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/config.rb:39:in `build'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/supervisor.rb:627:in `configure'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/lib/fluent/command/fluentd.rb:329:in `<top (required)>'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /fluentd/vendor/bundle/ruby/2.6.0/gems/fluentd-1.10.2/bin/fluentd:8:in `<top (required)>'
	from /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `load'
	from /fluentd/vendor/bundle/ruby/2.6.0/bin/fluentd:23:in `<main>'
```

I built the cloudwatch image.

**Comment by repeatedly** [comment]
@elsesiy You use v1.10.2 image. How about v1.10.3 image?

**Comment by elsesiy** [comment]
@repeatedly I see the error, my bad. It should be `/usr/env/bin sh` and not the other way around

**Comment by elsesiy** [comment]
I'll create a fix for this in 5min

**Pull request merged**
