### PR TITLE
Add AWS Elasticsearch image

### PR DESCRIPTION
**Pull request by AdrienKuhn**
This PR adds `debian-awselasticsearch` docker image. 

AWS ES service require requests signature. 

This image contains the [aws-elasticsearch-service fluent](https://github.com/atomita/fluent-plugin-aws-elasticsearch-service) plugin.

Authentication with AWS ES is done using EC2 instance profile.

### CODE REVIEW

**Comment by Jaykah** [comment]
Is anyone using this in production?

Also, any plans to merge?

Thanks!

**Comment by repeatedly** [comment]
Currently, no plan to merge because we have a problem to maintain contributed images.

https://github.com/fluent/fluentd-kubernetes-daemonset/issues/293

**Comment by danopia** [comment]
I've been using an older version of the same thing in production for at least a year now. Just switched production to this image because [I needed a newer elasticsearch plugin](https://github.com/uken/fluent-plugin-elasticsearch/issues/589#issuecomment-495520040). I also replace `/fluentd/etc` with my own configuration at the Kubernetes level, so that I can roll out new configs without making new images. Works well!

**Comment by gatolim** [comment]
@AdrienKuhn  thanks for coming up with the repo. I am new to the docker world and was playing around this. I have my ES set up in AWS and have docker for window set up locally. I cloned your repo and docker build the debian-awselasticsearch image however when I try to apply the image using fluentd-daemonset-awselasticsearch-rbac.yml I have the following error: 
[FATAL tini (6)] exec /fluentd/entrypoint.sh failed: No such file or directory

I verified that the build steps does copy this .sh file and the file existed in my build folder. Am I missing something ?

**Comment by AdrienKuhn** [comment]
@gatolim I tried to apply the `fluentd-daemonset-awselasticsearch-rbac.yml` file on my side and I didn't encounter any issue. 

I used the following (v1.7) image for test purposes: [krewh/fluentd-awselasticsearch](https://cloud.docker.com/repository/docker/krewh/fluentd-awselasticsearch/general).

**Comment by gatolim** [comment]
Thanks @AdrienKuhn, I ended up building my own image. I encountered the same problem while using my own and it turns out to be the end line char ('\r\n') difference between window and linux in the .sh file. I suspected it was the same cause when I use yours.

**Comment by wcarlsen** [comment]
We ended up using this proxy (https://github.com/abutaha/aws-es-proxy) as a sidecar, which allows us to use on of the pre built images of this repos. Works flawlessly, but the proxy image development is rather stale.

**Comment by Nuru** [comment]
> We ended up using this proxy (https://github.com/abutaha/aws-es-proxy) as a sidecar, which allows us to use on of the pre built images of this repos. Works flawlessly, but the proxy image development is rather stale.

@wcarlsen Did you really get `aws-es-proxy` to work flawlessly? Last time I tried it I had to reject it because if it encountered a 403 or 302 status code from Elasticsearch it would just swallow it and return an empty 200 to the caller. How did you fix this, or did you just decide it was acceptable behavior?

**Comment by wcarlsen** [comment]
@Nuru we probably shouldn't continue this here. But I wasn't aware of this behavior. I think it is a trade off between maintaining a fluentd image. We are currently investigating when we would expect to get a 302 or 403 from AWS ES. Maybe you have experience with this or have a better overview of how big a problem this actually is?

**Pull request closed without merging**
