### PR TITLE
Prometheus metrics added

### PR DESCRIPTION
**Pull request by gitirabassi**
Closing #93 and #97 

Added https://github.com/fluent/fluent-plugin-prometheus by default on port 24231

### CODE REVIEW

**Comment by schndr** [comment]
Howdy, any support needed? lgtm

**Comment by max-rocket-internet** [comment]
@gitirabassi can you rebase to fix the conflicts?

@repeatedly can we get this reviewed? A lot of people are interested in prometheus support 😃

**Comment by max-rocket-internet** [comment]
@repeatedly there have also been 2 other PRs to try and address this: https://github.com/fluent/fluentd-kubernetes-daemonset/pull/96 https://github.com/fluent/fluentd-kubernetes-daemonset/pull/97

**Comment by repeatedly** [comment]
Currently, v0.12 images are outedated so no need to apply changes to v0.12 images.
In addition, this PR has only `prometheus` input plugin. Is it enough?

**Comment by max-rocket-internet** [comment]
@repeatedly it seems this PR might be dead. I will make a new one. A question though: is it possible to enable/disable plugins based on an env var? Because it would be nice to have prometheus support optional but easy to enable.

**Comment by repeatedly** [comment]
@max-rocket-internet Currently, no envver based if in configuration syntax but we can use `@include` approach to emulate it.

https://github.com/fluent/fluentd-kubernetes-daemonset#disable-systemd-input
https://github.com/fluent/fluentd-kubernetes-daemonset/blob/6fa634a8dd02daf826b5a914fddd8b2cbed5aba4/templates/conf/fluent.conf.erb#L8

`@include` ignores error when target file is missing.

**Comment by max-rocket-internet** [comment]
OK good idea @repeatedly, thanks! See here: https://github.com/fluent/fluentd-kubernetes-daemonset/pull/287

**Pull request closed without merging**
