### PR TITLE
Support for AMQP

### PR DESCRIPTION
**Pull request by mmailhos**

### CODE REVIEW

**Comment by jojotheboss** [comment]
Hi, I really need that PR. Please merge :-)

**Comment by warmfusion** [comment]
Out of my own curiosity, any reason this PR doesn't use the giraffi based fluent-plugin-amqp - I'm a contributor on that project and am about to start deploying the plugin onto our own kubernetes clusters so if you're aware of a known problem with it, i'll need to go fix it :-)

**Comment by jojotheboss** [comment]
Any news concerning this PR ?

**Comment by Maxpain177** [comment]
Any news?

**Comment by jojotheboss** [comment]
Still no merge ?

**Comment by repeatedly** [comment]
Yes. Currently, we don't want to merge such patches because it is not good for users. We need to find good way for maintaining third party images.
Maybe, patch author will publish on docker hub.

**Comment by repeatedly** [comment]
I just opened new issue for current concern: https://github.com/fluent/fluentd-kubernetes-daemonset/issues/293

**Pull request closed without merging**
