### PR TITLE
Release v1.16.6-1.3

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Comment by kenhys** [comment]
should be rebased after #1551 was merged into v1.16 branch.

**Comment by kenhys** [comment]
Rebased with v1.16 branch.

**Comment by Watson1978** [comment]
[Q] Looks like that there are some files that have not applied #1551 changing.
Is this expected?

```
$ grep --files-without-match "IPAddr.new(host).ipv6?" -r docker-image/v1.16/ | grep "kubernetes.conf"
docker-image/v1.16/debian-stackdriver/conf/kubernetes.conf
docker-image/v1.16/debian-elasticsearch6/conf/kubernetes.conf
docker-image/v1.16/arm64/debian-stackdriver/conf/kubernetes.conf
docker-image/v1.16/arm64/debian-elasticsearch6/conf/kubernetes.conf
```

**Comment by kenhys** [comment]
elasticsearch6 and stackdriver images were not supported anymore.

https://github.com/fluent/fluentd-kubernetes-daemonset/commit/c01c4f380f34e2887084285282bf6f87d91ce887
https://github.com/fluent/fluentd-kubernetes-daemonset/commit/e74a90cfb554aa254f1f45146d91826d34f1eab6

**Review by Watson1978 — APPROVED** [review]
👍🏻

**Comment by kenhys** [comment]
Now created tag for deploy v1.16.6-1.3
https://github.com/fluent/fluentd-kubernetes-daemonset/actions/runs/12423945413

**Pull request merged**
