### PR TITLE
install gem bundler for debian images

### LINKED ISSUE #147: gem bundler missing from debian images
Using image `v1.2-debian-elasticsearch` trying to include custom Gem specs via Gemfile which is mounted in at run time.

Set `FLUENTD_DISABLE_BUNDLER_INJECTION=0` so that the runtime bundler is executed.

Container fails to start because gem bundler is not installed.
```
error: Could not find 'bundler' (>= 0) among 49 total gem(s)
Checked in 'GEM_PATH=/fluentd/vendor/bundle/ruby/2.3.0', execute `gem env` for more information
```

Fix: `gem install bundler`

### PR DESCRIPTION
**Pull request by therealgambo**
Fixes #147 

@repeatedly LGTM

### CODE REVIEW

**Comment by errm** [comment]
You should not need to install bundler via the system package `ruby-bundler` and with rubygems ... if we need it to be installed with rubygems please remove the system package...

**Comment by therealgambo** [comment]
Removed system package in favour of rubygems.

@errm lgtm

**Comment by therealgambo** [comment]
Done.

**Comment by errm** [comment]
Nice LGTM

**Comment by repeatedly** [comment]
Thanks. Just merged.

@errm Thanks for the reviews 👍

**Pull request merged**
