### PR TITLE
kafka is used with zookeeper

### PR DESCRIPTION
**Pull request by pyama86**
Hi!
I want to use `fluent-plugin-zookeeper`  because I want to write such a configuration.

```ruby
<match **>
  @type kafka_buffered
  zookeeper zookeeper.service.consul:2181
  zookeeper_path /cluster/brokers/ids
  output_include_tag true
  output_include_time true
</match>
```
Please study my suggestion.

### CODE REVIEW

**Comment by pyama86** [comment]
> Do you want to install zookeeper gem to use zookeeper and zookeeper_path option in fluent-plugin-kafka?

yes!It is necessary to use zookeeper.

https://github.com/fluent/fluent-plugin-kafka

> If you want to use zookeeper related parameters, you also need to install zookeeper gem. zookeeper gem includes native extension, so development tools are needed, e.g. ruby-devel, gcc, make and etc.

**Comment by ganmacs** [comment]
So, Why not install only zookeeper gem? I think installing zookeeper gem is enough to achieve what you want.

**Comment by pyama86** [comment]
oh! sorry.
I had a misunderstanding. to correct.

**Comment by pyama86** [comment]
Let me ask you one question.
Gemfile.lock updated automatically at release?

**Comment by ganmacs** [comment]
> Gemfile.lock updated automatically at release?

I don't think so. `make src-all` would update all Gemfile.lock  (Is this right @repeatedly ?).

**Comment by pyama86** [comment]
I update Gemfile.lock.
Is there anything else you need?

**Comment by repeatedly** [comment]
No need more task. Thanks. New image will be published soon.

**Comment by pyama86** [comment]
thanks!

**Pull request merged**
