### PR TITLE
amd64: arm64: Add kafka2 image

### PR DESCRIPTION
**Pull request by cosmo0920**
Fixes https://github.com/fluent/fluentd-kubernetes-daemonset/issues/456

out_kafka_buffered is marked as deprecated.
We should start to provide out_kafka2 based images.

Signed-off-by: Hiroshi Hatake <hatake@clear-code.com>

### CODE REVIEW

**Comment by repeatedly** [comment]
Could you update README to mention kafka2 is better?

**Comment by cosmo0920** [comment]
Sure. Will do.

**Comment by cosmo0920** [comment]
I'd added kafka image suggestion section as note:
https://github.com/fluent/fluentd-kubernetes-daemonset/pull/503/commits/f2ac5c30145fc7ea7fe0de8afbd33943c3a9410e

**Review by repeatedly — APPROVED** [review]
Good!

**Pull request merged**
