### PR TITLE
Extend environment variable for syslog image

### LINKED ISSUE #271: fluentd syslog output plugin to send logs to remote syslog server with TLS
I am new to fluentd and am able to collect logs from Kubernetes cluster, however I am hoping to send logs to a remote syslog server with ssl and cert file.

Is there a TLS supported output syslog implementation right now?

### PR DESCRIPTION
**Pull request by tongpu**
Primary goal is to allow configuration of TLS parameters, but
additionally all other relevant variables can now also be defined via
environment variables.

Fixes #271

### CODE REVIEW

**Comment by tongpu** [comment]
fluent-plugin-kubernetes_remote_syslog needs to roll a more recent release to enable the functionality, because it's not included in 0.3.6. :(

**Comment by repeatedly** [comment]
Need this change?

**Comment by tongpu** [comment]
@repeatedly That would be OK too. I've lost track how many forks of the remote_syslog plugin exist currently, but I would need one that allows me to specify the `tls` and `ca_file` configuration at least. The changes in #211 would help with getting this PR merged.

**Comment by repeatedly** [comment]
Close via #306

**Pull request closed without merging**
