### PR TITLE
Runtime settings support

### PR DESCRIPTION
**Pull request by jrottenberg**
Adding entyrpoint so we can have runtime settings modifying the configuration.

Ideally that should address the concern pointed out on #41

### CODE REVIEW

**Comment by jrottenberg** [comment]
You can test it on : quay.io/jrottenberg/fluent2es:runtime-aws-es-user-passwd

**Comment by creactiviti** [comment]
+1 @jrottenberg thanks for the patch. Exactly what I needed.

**Comment by repeatedly** [comment]
@edsiper Can we merge this or do you have any concern?

**Comment by onlydole** [comment]
@edsiper / @repeatedly - What else might need to be done before merging this in?

**Comment by repeatedly** [comment]
@edsiper how about adding more maintainers to this repository?
We are sometimes busy for supporting new features and adapting new k8s features.
Adding more active maintainers is good for users and community.

**Comment by toddams** [comment]
Any update on this?

**Comment by onlydole** [comment]
Will this pull request be accepted anytime soon?

**Pull request merged**
