### PR TITLE
Add moreoptions for elasticsearch config

### PR DESCRIPTION
**Pull request by zopanix**
Hey,

I'm proposing a pull request that just allows people to have a more customized setup with you docker image.

If you need me to create an issue for this please tell me.

Info:
Added two configs for elasticsearch:
* reload_connections: Adding this as possible env variable will allow people that use AWS ES to disable the feature. I know there is a separate plugin for aws, but I'd like to stick with the original ES plugin. Adding this is a quick win for most people and doesn't interfere with how it works today
* logstash_prefix: Another quick win allowing to customize the indexes used by fluent for ES

### CODE REVIEW

**Comment by edsiper** [comment]
thanks

**Comment by edsiper** [comment]
@chancez thanks, #28 merged.

**Comment by zopanix** [comment]
@edsiper @chanez: I think the problem is with your automated build in docker hub not working anymore for sometime. They still use the old tags

**Comment by chancez** [comment]
@zopanix that's part of it, but also my original statement is also true: this PR didn't regenerate the dockerfiles and configs, so this change wouldn't have resulted in updated images, even if builds were working.

**Comment by zopanix** [comment]
Okay sure, any idea on when they'll start working again ? @chancez @edsiper

**Comment by chancez** [comment]
Shortly

**Comment by zopanix** [comment]
@chancez: cool thx

**Pull request merged**
