### PR TITLE
Upgrade Fluentd to 1.4 and Ruby to 2.6

### PR DESCRIPTION
**Pull request by moleskin-smile**
Upgrade Fluentd to 1.4.
Upgrade Ruby to 2.6 for images using Fluentd 1.4 by utilizing upstream Ruby 2.6 images.

No functional changes in current 1.3 images (with exception for regenerated Gemfile.locks).

Fixes fluent/fluentd-kubernetes-daemonset#241 for me.

### CODE REVIEW

**Comment by moleskin-smile** [comment]
https://github.com/fluent/fluentd-docker-image/pull/178 was merged. This one is now ready for review.

**Comment by repeatedly** [comment]
No need to keep to support v1.3 code in templates for v1.4. You can remove v1.3 list from Makefile.
And don't include v1.3 image update.

In addition, don't need to sync image version with fluentd-docker-image.

```
v1.4/debian-elasticsearch:v1.4.2-debian-elasticsearch-1.0,v1.4-debian-elasticsearch-1 \
```

1.0 is enough for new k8s daemonset images. We don't have a support plan for ruby2.3 and fluentd v1.4 combo for k8s daemonset.

**Comment by moleskin-smile** [comment]
@repeatedly: thanks for the review. I've removed v1.3 images from `Makefile`, added them statically to `README.md.erb` file, reverted all changes to generated v1.3 configurations and reverted these version bumps you've pointed out.

**Comment by repeatedly** [comment]
Sorry for the late. Thanks!
I will build these images soon.

**Comment by repeatedly** [comment]
I tried to build these images but our docker hub hits the issue for updating build rules.

https://success.docker.com/article/i-have-issues-triggering-autobuilds

The case is similar to last case. I'm now contacting docker support to resolve the problem.

**Pull request merged**
