### PR TITLE
Add v1.17.0-1.0 images

### PR DESCRIPTION
**Pull request by kenhys**
As fluent-plugin-kubernetes_metadata_filter has supported fluentd v1.17.0 since 3.5.0.

### CODE REVIEW

**Comment by kenhys** [comment]
workflow should be modified after #1496 has been merged.

**Comment by kenhys** [comment]
Updated target for v1.17 in workflow.
and re-generated dockerfiles.

**Review by daipom — COMMENTED** [review]
Do we need these files?

* `docker-image/v1.17/{,arm64/}debian-elasticsearch6/`
* `docker-image/v1.17/{,arm64/}debian-stackdriver/`
* `plugins/v1.17/elasticsearch6/`
* `plugins/v1.17/stackdriver/`

Does the current Makefile make `docker-image/v1.17/debian-elasticsearch6/` and `docker-image/v1.17/debian-stackdriver/`?
Looks like they have been already removed from the Makefile.

**Comment by daipom** [comment]
Sorry, I can't find how to manage `plugins/` in [MAINTAINING.md](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/b75789ce4e9bd53044177597a972cfdd440b6201/MAINTAINING.md) and don't understand it.
Do we need to manually create the corresponding empty directories?

**Comment by kenhys** [comment]
plugins/v1.17 is treated as template and copy to docker-image/v1.17/ each images by plugins rule in Makefile.

**Comment by daipom** [comment]
> Do we need these files?
> 
>     * `docker-image/v1.17/{,arm64/}debian-elasticsearch6/`
> 
>     * `docker-image/v1.17/{,arm64/}debian-stackdriver/`

The `arm64` files remain.
Shouldn't we remove those files as well?

**Comment by kenhys** [comment]
Thanks, that's right.
I've remove it too.

**Review by daipom — APPROVED** [review]
LGTM. Thanks!

https://github.com/fluent/fluentd-kubernetes-daemonset/pull/1495#issuecomment-2188110208
> thus plugins has to be manually created every new v1.1x release.

Maybe we should add this flow to [MAINTAINING.md](https://github.com/fluent/fluentd-kubernetes-daemonset/blob/b75789ce4e9bd53044177597a972cfdd440b6201/MAINTAINING.md) later.

**Pull request merged**
